blank_issues_enabled: true
contact_links:
  - name: Questions and discussion
    url: https://github.com/nrupala/sllm/discussions
    about: Ask questions and discuss ideas in Discussions
  - name: Support this work
    url: https://github.com/sponsors/nrupala
    about: Sponsor the development of this project on GitHub Sponsors
